language: python
python: 3.6
addons:
  rethinkdb: "2.3"

install:
  - pip install pycodestyle flake8 isort
  - pip install -r requirements.txt
  - pip install -U pytest
  - cp settings.example.yml settings.yml
  - python install.py

script:
  # Checking for pep8 issues.
  - pycodestyle --show-source --max-line-length=120 --show-pep8 .

  # Running some tests.
  - pytest Testing.py
