language: python
python: 3.6

install:
  - pip install pycodestyle flake8 isort
  - pip install -r /path/to/requirements.txt

script:
  - pycodestyle --show-source --max-line-length=120 --show-pep8 .
